name: Clear Notebook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repository content to gitHub runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install nbconvert
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4
      - name: Look up and clear Notebooks
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.ipynb ]]
            then
              jupyter nbconvert --clear-output --inplace $file
              
              git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
              git config --global user.name "${GH_USERNAME}"
              git add $file
              git commit -m "commit message"
              git push
            fi
          done
        env:
          GH_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}