name: Clear Notebook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repository content to gitHub runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install nbconvert
      - run: pip install nbformat
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4
      - name: List all changed files
        run: |
          notebooks=${{ steps.changed-files.outputs.all_changed_files }}
          if [ ! -z "$notebooks" ]
          then
              # Run the script to clear the notebooks
              python .githooks/clear_notebooks.py $notebooks
              # Re-add notebooks to staging area
              git add $notebooks
          fi