name: Clear Notebook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repository content to gitHub runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install nbconvert
      - run: pip install nbformat
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4
      - name: Look up and clear Notebooks
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.ipynb ]]
            jupyter nbconvert --clear-output --inplace $file
            git add $file
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}